title: Eclectic
description: Language, computing, and other topics
copyright: "© 2008 — 2026 David Chappell"
authors:
  "David Chappell":
    photo: /assets/images/author.jpg
    blurb: >
      A computer programmer with 25 years of experience using and creating web technology.
      He enjoys applying his skills to the creation of language-teaching materials. 
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "David Chappell" 
      excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title
#google_analytics: UA-48777822-8
